import './index.html'
import './elements.html'
import './assets/css/style.css'
import './assets/css/bootstrap-theme.min.css'
import './assets/css/owl.carousel.css'
import './assets/css/owl.theme.default.min.css'
import './assets/css/magnific-popup.css'
import './assets/css/bootstrap.min.css'
import './assets/js/jquery-3.1.1'
import './assets/js/jquery.magnific-popup'
import './assets/js/script.js'
import './assets/js/bootstrap.min'
import './assets/js/jquery.magnific-popup.min'
import './assets/js/owl.carousel.min'

